# LeadFlow AI - Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: leadflow-backend
  namespace: leadflow-ai
  labels:
    app: leadflow-backend
    component: api
    environment: production
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: leadflow-backend
  template:
    metadata:
      labels:
        app: leadflow-backend
        component: api
        environment: production
    spec:
      serviceAccountName: leadflow-backend
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: backend
        image: ghcr.io/leadflow-ai/platform/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: leadflow-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: leadflow-secrets
              key: redis-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: leadflow-secrets
              key: jwt-secret
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: leadflow-secrets
              key: openai-api-key
        - name: PROPSTREAM_API_KEY
          valueFrom:
            secretKeyRef:
              name: leadflow-secrets
              key: propstream-api-key
        - name: BATCHSKIPTRACE_API_KEY
          valueFrom:
            secretKeyRef:
              name: leadflow-secrets
              key: batchskiptrace-api-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/ready
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: cache
          mountPath: /app/.cache
      volumes:
      - name: tmp
        emptyDir: {}
      - name: cache
        emptyDir: {}
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - key: "kubernetes.io/arch"
        operator: "Equal"
        value: "amd64"
        effect: "NoSchedule"

---
apiVersion: v1
kind: Service
metadata:
  name: leadflow-backend-service
  namespace: leadflow-ai
  labels:
    app: leadflow-backend
    component: api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: leadflow-backend

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: leadflow-backend
  namespace: leadflow-ai
  labels:
    app: leadflow-backend
